// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eslkbnvcqbnabeemzzod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbGtibnZjcWJuYWJlZW16em9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjA2NjksImV4cCI6MjA3MDczNjY2OX0.HMAB-8MIQF9wFPJqOU0fto103lR83WcQkk1VfXDLawQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});